SCHEMA_VERSION = "dev-0.2"
WEBRTC_SCHEMA_VERSION = "dev-0.3"
# 단어 구간 메시지(word_start / word_end).
WORD_SCHEMA_VERSION = "dev-0.4"
SUPPORTED_SCHEMA_VERSIONS = {
    SCHEMA_VERSION,
    WEBRTC_SCHEMA_VERSION,
    WORD_SCHEMA_VERSION,
}
MAX_FRAME_BYTES = 262_144
